name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and push Docker images
        run: |
          # Build both images
          docker-compose -f docker-compose.yml build
       
          docker tag recipe-shop_web-client:latest recipe-shop/recipe-shop-web-client:latest
          docker push recipe-shop/recipe-shop-web-client:latest

          docker tag recipe-shop_server:latest recipe-shop/recipe-shop-server:latest
          docker push recipe-shop/recipe-shop-server:latest
