# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main","update-CI-pipeline-1" ]
  pull_request:
    branches: [ "main" ]

jobs:
  upload_secrets:

    runs-on: ubuntu-latest

    steps:
    - name: Echo secrets
      working-directory: ./Recipe-Shop
      run: |
          echo $TEST_ENV_FILE >> server/.env
          cat server/.env
      shell: bash
      env:
          # Feel free to rename this variable, but make sure to update it everywhere. You should paste your entire file in your secrets
          TEST_ENV_FILE : ${{secrets.KEY}}
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DEV_ENV_FILE
        path: server/.env

  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: |
          npm run install_all

      - name: Build Project
        run: |
          cd web-client
          npm run build
          
      - name: Test Project
        run: |
          npm run test_all
   
   
